- Intro
- What is Nevergrind? Developed publically since 2012
- What are its influences?
- Brief history as fangame and its conversion
- That means I needed to hire artists! What did I need?
- Let's talk about the budget!
	- Due to it's small budget I decided to take a risk and front the budget though I would greatly appreciate if you back the project.
	- By funding the project this way, I can guarantee that I deliver the final product.
- By backing Nevergrind you are:
	- promoting indie game development
	- promoting the future of browser games
	- helps keep the project ad free
- Server accounts will make the game more enjoyable! 
	- No more data wipes!
	- Play on any device with a browser!
	- Enables future features like chat, sharing player profiles, mailbox, and even trade!
- Volunteers from our forums have been helping test
- Like what you see? Back the project and check out the rewards and stretch goals.
- Thank you for watching!